# Generated by Django 5.1.6 on 2025-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_roadmap_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='completed_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
